### ISSUE TITLE
Add Safari 11 data

### ISSUE THREAD

**Issue by othermaciej** [GoogleChrome/confluence#162]
It would be helpful if Safari 11 data could be added, either based on the most recent beta, or soon when it actually ships.

**Comment by othermaciej** [comment]
Specifically, this would make the "failure to ship" data more useful since Safari 11 likely ships many of the mentioned APIs.

**Comment by foolip** [comment]
We're using BrowserStack to collect the data, do you know if new releases normally show up there quickly? @mdittmer are there any cases where you've done ad-hoc runs on physical machines to get new data in there? Is there any issue for automatically finding and running new releases that show up in BrowserStack, or does that already happen?

**Comment by RByers** [comment]
Yeah definitely we need to get Safari 11 data added ASAP.  It seems like it can sometimes take awhile for Browserstack to update (they have a STP build under El Capitan, but it's an old Safari 9 STP!).  Perhaps it's worth doing a one-off manual run on one of our macs if it's not too difficult and won't cause problems down the line when we re-generate data from Browserstack?

**Comment by foolip** [comment]
Per https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html it looks like it's already released. I agree that doing a one-off manual run just to get the data in would be great!

**Comment by mdittmer** [comment]
I tried installing the latest Safari Technology Preview for MacOS 10.12.6, but I got this:

```zsh
/Applications/Safari\ Technology\ Preview.app/Contents/MacOS/Safari\ Technology\ Preview 
2017-09-21 15:57:52.214 Safari Technology Preview[1235:9010] +[SimServiceContext sharedServiceContextForDeveloperDir:error:]: unrecognized selector sent to class 0x10aa908c8
2017-09-21 15:57:52.226 Safari Technology Preview[1235:9010] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[SimServiceContext sharedServiceContextForDeveloperDir:error:]: unrecognized selector sent to class 0x10aa908c8'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa43232cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb913348d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffa43a4e44 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffa4295755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffa42952a8 _CF_forwarding_prep_0 + 120
	5   WebInspector                        0x000000010414adb4 -[RWIManager init] + 671
	6   WebInspector                        0x000000010414aae9 +[RWIManager sharedManager] + 255
	7   Safari                              0x00000001020817bd -[DevelopMenuController installMenu] + 2654
	8   Safari                              0x0000000101e747da -[AppController awakeFromNib] + 1827
	9   CoreFoundation                      0x00007fffa429bff9 -[NSSet makeObjectsPerformSelector:] + 217
	10  AppKit                              0x00007fffa1d608bb -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1442
	11  AppKit                              0x00007fffa1d57af0 loadNib + 375
	12  AppKit                              0x00007fffa1d5703a +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 308
	13  AppKit                              0x00007fffa1d56df2 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
	14  AppKit                              0x00007fffa1d56baf +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 414
	15  AppKit                              0x00007fffa1d51b2b NSApplicationMain + 498
	16  libdyld.dylib                       0x00007fffb9a19235 start + 1
	17  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      
```

😿

**Comment by cdumez** [comment]
Did you use https://secure-appldnld.apple.com/STP/091-33444-20170919-603056FA-9D74-11E7-929D-F7CEFCD6B433/SafariTechnologyPreview.dmg ? You may be using the High Sierra STP build on Sierra.

**Comment by cdumez** [comment]
Got this link from:
https://developer.apple.com/safari/download/

"Safari Technology Preview for macOS Sierra" link since you're using 10.12, not 10.13.

**Comment by cdumez** [comment]
Also note that this bug is about Safari 11, not Safari Technology Preview. To get Safari 11, you would need to upgrade to MacOS 10.13 "High Sierra".

**Comment by mdittmer** [comment]
I did follow the "Sierra", not "High Sierra" link from https://developer.apple.com/safari/download/, and I am running Sierra. Am I doing something wrong? Do I need to update some libraries (XCode perhaps?)

**Comment by cdumez** [comment]
@mdittmer Ok, then I do not know what the problem is, sorry.

**Comment by cdumez** [comment]
@mdittmer I pinged some people about this internally. Will follow-up when they come back to me.

**Comment by cdumez** [comment]
@mdittmer This is apparently a known issue :/ Updating Xcode / SDK *should* work. You can also try again with the next STP (41).

**Comment by othermaciej** [comment]
Note that the current STP has a significantly newer WebKit than Safari 11. Having STP data would be kind of neat but it's not a good substitute for Safari 11.

**Comment by mdittmer** [comment]
Was Safari 11 released for MacOS 10.12.6 or do I need to get my hands on a machine with High Sierra to try Safari 11? My experience with official releases has been that I only get them when Apple decides to push an update to my machine (i.e., for my OS version).

**Comment by othermaciej** [comment]
According to rumor sites, macOS 10.3 High Sierra will be available on September 25. We usually ship major Safari versions to previous major OS versions. In the meantime, the best option to get a very close approximation of Safari 11 is to install a High Sierra public beta.

This page claims to point to a Safari 11 beta for macOS Sierra or OS X El Capitan, but I was unable to get an actual download; I'll look into why https://developer.apple.com/safari/download/

**Comment by othermaciej** [comment]
Correction: Safari 11 has already shipped for Sierra and El Capitan. You can update to it via the Mac App Store app in the Updates tab.

**Comment by mdittmer** [comment]
Thanks for looking into it. Not sure why it isn't listed as an update for me. I'll try a different machine.

**Comment by foolip** [comment]
@mdittmer, if you're using a Google-issues MacBook it's possible updates are held back to provide for some kind of controlled rollout, at least for full OS upgrades that seems to happen. I also don't have the option to upgrade to Safari 11 yet, on macOS Sierra.

**Comment by foolip** [comment]
I've audited Safari 11 removals from a preview, and almost all changes make sense and could be tracked down to recent WebKit changes, often by @cdumez.

The only one that does not make sense is Navigator.hardwareConcurrency, which the data claims is removed but is still listed in https://webkit.org/status/#feature-navigator.hardwareconcurrency

@mdittmer, can you check if it's really removed?

**Comment by foolip** [comment]
I've also gone over the additions, and they all make sense, notable additions are WebRTC (yay @youennf) and WebGL, a really impressive set of new features I have to say.

@mdittmer, other than hardwareConcurrency, I think the changes for Safari 11 are probably correct.

**Comment by othermaciej** [comment]
hardwareConcurrency was genuinely removed per https://bugs.webkit.org/show_bug.cgi?id=174400

**Comment by othermaciej** [comment]
(We need to update the feature status page I guess)

**Comment by othermaciej** [comment]
From spot-checking the list of claimed "failure to ship" for Safari 11, I don't see anything obviously wrong, but I didn't do any testing or study of the code to confirm (yet).

**Comment by RByers** [comment]
Great!  I've also done a pass over the Safari 11 failure to ship and found just a couple issues (see https://github.com/GoogleChrome/confluence/issues/163#issuecomment-332282297).  Let's call this done and open new bugs for anything else we discover.
