### ISSUE TITLE
Graph y-axis should be 0-based

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/confluence#164]
I just realized the browser-specific graph looks pretty misleading with Chrome and Safari way down at the bottom.  The Y-axis seems to start around 200.  I think we should probably make them 0-based to get a better scale.

**Comment by RByers** [comment]
Assuming this is trivial, let's call it urgent.  I'm worried that it makes Chrome look better than it is - that's the kind of bias that could make us look bad and hurt people's confidence in the impartiality of this data.

**Comment by RByers** [comment]
This is fixed but not yet rolled out, right @mdittmer?

**Comment by mdittmer** [comment]
This is fixed in prod.
