### ISSUE TITLE
Doesn't scroll on Firefox or Firefox

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/confluence#165]
Well this is embarrassing 😉. Our interop dashboard is unusable in Firefox because it doesn't scroll due to an `overflow:hidden` rule on body.  We should figure out why Chrome and Firefox behave differently in that regard (@bokand do you know?).  But separately let's just fix it ASAP.

**Comment by bokand** [comment]
Weird, this is a scrolling <div> which should work the same in both. I filed https://webcompat.com/issues/10168

There is a well known difference if pinch-zoom is involved and it's on the main window. See https://bugzilla.mozilla.org/show_bug.cgi?id=1336346 which was closed in favor of the "support visual viewport pinch-zoom" bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1123938. But it seems like neither of these is the case here.

**Comment by karlcow** [comment]
My pull request https://github.com/GoogleChrome/confluence/pull/168 for https://github.com/webcompat/web-bugs/issues/10168

**Comment by bzbarsky** [comment]
For what it's worth, the real difference is that the `<div class="content ng-scope">` child of the `<ui-view class="ng-scope">` child of `<main>` is tall enough for its kids in Gecko (hence doesn't scroll, but you get overflow higher up the tree which is hidden due to the "overflow:hidden" bits), but is NOT tall enough for its kids in Blink (and hence gets a scrollbar).  

//cc @dholbert

**Comment by bzbarsky** [comment]
There's a good chance (per mail from @dholbert, but without having fully investigated) that this page is depending on a longstanding bug in Chrome implementation of flexbox.  See https://bugs.chromium.org/p/chromium/issues/detail?id=487302

**Comment by dholbert** [comment]
Indeed. See explanation in https://github.com/webcompat/web-bugs/issues/10168#issuecomment-331241775

Bottom-line, you need to add `min-height:0` for the elements `main`, `ui-view`, and `.tab-content` or else the flexbox spec says they can't be any smaller than their content height (which is quite tall).

**Comment by bzbarsky** [comment]
I assume the title meant to say "or Edge"...

**Comment by foolip** [comment]
Fixed the title, thanks!
