### ISSUE TITLE
failure to ship description makes no sense

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChrome/confluence#169]
The blurb below the graph says:

> It measures the number of APIs that each browser provides for the duration of the Grace Period, but all other browsers do provide throughout the Grace Period.

There must be some negations missing somewhere in there, but I'm not quite sure where.

**Comment by othermaciej** [comment]
In context the term "Grace Period" is also weird and doesn't fit the description. Here's a suggested rewording.

Instead of this: 

> This metric is computed relative to a one-year "Grace Period" prior to each data point. It measures the number of APIs that each browser provides for the duration of the Grace Period, but all other browsers do provide throughout the Grace Period.

How about something like this:

> This metric measures the number of APIs that are missing in a each browser release, but which were already shipping in all other browsers for at least a year prior to that release.

**Comment by mdittmer** [comment]
Thanks for the suggestions!

> This metric measures the number of APIs that are missing in a each browser release, but which were already shipping in all other browsers for at least a year prior to that release.

The missing piece here is that APIs are listed iff the browser being measured did not ship the API in *all releases* that were released during the Grace Period. @othermaciej do you think omitting that detail in favour of a simpler definition is worth it? @foolip WDYT?

**Comment by othermaciej** [comment]
@mdittmer Let me see if I understand what you're saying. Let's use this example:

- FunBrowser 3.0 ships on June 6, 2012. It include support for the Foo.bar() API.
- FunBrowser 4.0 ships on July 6, 2012. Support for the Foo.bar() API has been removed.
- All other browsers have shipped the API for the whole period starting July 6, 2011.

Under the definition you describe, it sounds like FunBrowser 4.0 would not be dinged for "failure to ship". Even though it's missing an API that is in all other browsers, it was in another version in the past year.

I guess when this happens, it could be a case of "aggressive removal" in FunBrowser 4.0, or it could be a case of shipping something broken in FunBrowser 3.0 and then pulling it back.

To continue to exclude this case from "failure to ship", how about something like this:

> This metric measures the number of APIs that are missing in a each browser release, but which were already shipping in all other browsers for at least a year prior to that release. As an exception, if the API shipped in an earlier version of the same browser during the year prior, that doesn't count as a failure to ship. Depending on circumstances, it might be counted as an aggressive removal instead.

**Comment by foolip** [comment]
Keeping the existing definition, I think what @othermaciej makes sense. I think the distinguishing feature compared to "aggressive removal" is that "failure to ship" is something that this browser never had.

I also wonder if this would be simpler to understand and explain if only the releases at the beginning and end of the grace period matter. There could be a flip-flop in between, but ignoring that would make for much fewer browsers releases in the "proof" views that list the concrete APIs.

**Comment by bzbarsky** [comment]
Please s/a each/each/ in the suggestions above.  ;)

**Comment by RByers** [comment]
I'd argue that at least fixing the description to be approximately correct ("each browser *doesn't* 
provide" instead of "each browser provides") is urgent.  With that tiny tweak it at least makes sense.

**Comment by mdittmer** [comment]
This is fixed in prod.

**Comment by othermaciej** [comment]
It's still broken in the repository's .md file.

**Comment by othermaciej** [comment]
(I don't have the power to reopen, should I file a new issue for that?)

**Comment by foolip** [comment]
I'll reopen.

**Comment by mdittmer** [comment]
Oops! I thought it was only broken on the site itself. Thanks for pointing this out!

**Comment by foolip** [comment]
Now fixed by https://github.com/GoogleChrome/confluence/pull/244.
