### ISSUE TITLE
browser-specific APIs data seems to be fairly inaccurate

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChrome/confluence#171]
For example, it claims that Firefox is shipping 869 browser-specific APIs.  Amongst those APIs it includes `CSSStyleDeclaration['border-width']`.  I can assure you that every single browser ships this.

This affects pretty much every non-single-word CSS property.

Similarly, the site claims that CSSStyleDeclaration.WebkitBorderImage is supported only by Firefox.   That just doesn't match reality.

**Comment by mdittmer** [comment]
Tracking this issue at #174 where I posted a bunch of details about why our methods deal poorly with dash-separated `CSSStyleDeclaration` properties.
