### ISSUE TITLE
When looking at "failure to ship" data for old versions of Safari, it claims the APIs are missing in all versions of Safari

### ISSUE THREAD

**Issue by othermaciej** [GoogleChrome/confluence#172]
I'm not sure how to explain this more concisely. When following the "failure to ship" link for an old Safari version, such as Safari 7.1, it claims all APIs that are missing in Safari 7.1 are also missing in Safari 10. But when following a Safari 10 link, those same APIs do not show as missing.

Concrete example. When I follow this link (from a 7.1 Failure to Ship data point) and add Safari 10.1 manually to versions (not sure why it includes only 8.0 by default), it tells me that Array.copyWithin is not supported:

https://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Safari_537.85.17_OSX_10.8.5%22,%22Safari_534.59.8_OSX_10.6.8%22,%22Safari_536.30.1_OSX_10.7.5%22,%22Safari_537.85.17_OSX_10.8.5%22,%22Safari_537.85.17_OSX_10.9.5%22,%22Safari_600.8.9_OSX_10.10.5%22,%22Edge_13.10586_Windows_10.0%22,%22Edge_14.14393_Windows_10.0%22,%22Firefox_40.0_OSX_10.11%22,%22Firefox_41.0_OSX_10.11%22,%22Firefox_42.0_OSX_10.11%22,%22Firefox_43.0_OSX_10.11%22,%22Firefox_44.0_OSX_10.11%22,%22Firefox_45.0_OSX_10.11%22,%22Firefox_46.0_OSX_10.11%22,%22Firefox_47.0_OSX_10.11%22,%22Firefox_48.0_OSX_10.11%22,%22Chrome_45.0.2454.85_OSX_10.11.6%22,%22Chrome_46.0.2490.71_OSX_10.11.6%22,%22Chrome_47.0.2526.73_OSX_10.11.6%22,%22Chrome_48.0.2564.97_OSX_10.11.6%22,%22Chrome_49.0.2623.75_OSX_10.11.6%22,%22Chrome_50.0.2661.75_OSX_10.11.6%22,%22Chrome_51.0.2704.79_OSX_10.11.6%22,%22Chrome_52.0.2743.82_OSX_10.11.6%22%5D&releaseOptions=%7B%22Safari_537.85.17_OSX_10.8.5%22:false,%22Safari_534.59.8_OSX_10.6.8%22:false,%22Safari_536.30.1_OSX_10.7.5%22:false,%22Safari_537.85.17_OSX_10.9.5%22:false,%22Safari_600.8.9_OSX_10.10.5%22:false,%22Edge_13.10586_Windows_10.0%22:true,%22Edge_14.14393_Windows_10.0%22:true,%22Firefox_40.0_OSX_10.11%22:true,%22Firefox_41.0_OSX_10.11%22:true,%22Firefox_42.0_OSX_10.11%22:true,%22Firefox_43.0_OSX_10.11%22:true,%22Firefox_44.0_OSX_10.11%22:true,%22Firefox_45.0_OSX_10.11%22:true,%22Firefox_46.0_OSX_10.11%22:true,%22Firefox_47.0_OSX_10.11%22:true,%22Firefox_48.0_OSX_10.11%22:true,%22Chrome_45.0.2454.85_OSX_10.11.6%22:true,%22Chrome_46.0.2490.71_OSX_10.11.6%22:true,%22Chrome_47.0.2526.73_OSX_10.11.6%22:true,%22Chrome_48.0.2564.97_OSX_10.11.6%22:true,%22Chrome_49.0.2623.75_OSX_10.11.6%22:true,%22Chrome_50.0.2661.75_OSX_10.11.6%22:true,%22Chrome_51.0.2704.79_OSX_10.11.6%22:true,%22Chrome_52.0.2743.82_OSX_10.11.6%22:true%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22

But if I go to this link, there is no complaint about Array.copyWithin: https://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Safari_603.2.4_OSX_10.12.5%22,%22Safari_534.59.8_OSX_10.6.8%22,%22Safari_536.30.1_OSX_10.7.5%22,%22Safari_537.85.17_OSX_10.8.5%22,%22Safari_537.85.17_OSX_10.9.5%22,%22Safari_600.8.9_OSX_10.10.5%22,%22Safari_601.7.8_OSX_10.11.6%22,%22Safari_602.1.50_OSX_10.12%22,%22Safari_602.4.8_OSX_10.12.3%22,%22Safari_603.2.4_OSX_10.12.5%22,%22Firefox_49.0_OSX_10.11%22,%22Firefox_50.0_OSX_10.11%22,%22Firefox_51.0_OSX_10.11%22,%22Firefox_52.0_OSX_10.11%22,%22Firefox_53.0_OSX_10.11%22,%22Firefox_54.0_OSX_10.11%22,%22Firefox_55.0_OSX_10.11%22,%22Chrome_53.0.2785.101_Windows_10.0%22,%22Chrome_53.0.2785.113_Windows_10.0%22,%22Chrome_53.0.2785.89_Windows_10.0%22,%22Chrome_54.0.2840.59_Windows_10.0%22,%22Chrome_55.0.2883.75_Windows_10.0%22,%22Chrome_56.0.2924.87_Windows_10.0%22,%22Chrome_57.0.2987.110_Windows_10.0%22,%22Chrome_58.0.3029.81_Windows_10.0%22,%22Chrome_59.0.3071.86_Windows_10.0%22,%22Chrome_60.0.3112.78_Windows_10.0%22,%22Edge_15.15063_Windows_10.0%22%5D&releaseOptions=%7B%22Safari_603.2.4_OSX_10.12.5%22:false,%22Safari_534.59.8_OSX_10.6.8%22:false,%22Safari_536.30.1_OSX_10.7.5%22:false,%22Safari_537.85.17_OSX_10.8.5%22:false,%22Safari_537.85.17_OSX_10.9.5%22:false,%22Safari_600.8.9_OSX_10.10.5%22:false,%22Safari_601.7.8_OSX_10.11.6%22:false,%22Safari_602.1.50_OSX_10.12%22:false,%22Safari_602.4.8_OSX_10.12.3%22:false,%22Firefox_49.0_OSX_10.11%22:true,%22Firefox_50.0_OSX_10.11%22:true,%22Firefox_51.0_OSX_10.11%22:true,%22Firefox_52.0_OSX_10.11%22:true,%22Firefox_53.0_OSX_10.11%22:true,%22Firefox_54.0_OSX_10.11%22:true,%22Firefox_55.0_OSX_10.11%22:true,%22Chrome_53.0.2785.101_Windows_10.0%22:true,%22Chrome_53.0.2785.113_Windows_10.0%22:true,%22Chrome_53.0.2785.89_Windows_10.0%22:true,%22Chrome_54.0.2840.59_Windows_10.0%22:true,%22Chrome_55.0.2883.75_Windows_10.0%22:true,%22Chrome_56.0.2924.87_Windows_10.0%22:true,%22Chrome_57.0.2987.110_Windows_10.0%22:true,%22Chrome_58.0.3029.81_Windows_10.0%22:true,%22Chrome_59.0.3071.86_Windows_10.0%22:true,%22Chrome_60.0.3112.78_Windows_10.0%22:true,%22Edge_15.15063_Windows_10.0%22:true%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22

This is super confusing. If the data displayed is actually locked to just one version of each browser, it shouldn't show a spread of multiple versions.

**Comment by mdittmer** [comment]
This needs urgent fixing! We keep getting issues that all stem from #127. The `releaseOptions` and `numAvailable` parameters in the URL provide an (admittedly hacky) way to show exactly the right APIs for a data point **so long as you don't add or remove releases**.

Short term fix: We need to update the view controller for data-point-based views to prevent adding and removing releases.

Long term fix: Perhaps we should have a different way of interacting with "lists of APIs" that are based on data points. Using the same catalog view seems to be confusing.

**Comment by mdittmer** [comment]
I'm closing this as a special case of #127.
