### ISSUE TITLE
Data are misleading on CSSStyleDeclaration's dash-separated properties

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/confluence#174]
After doing some investigations [this view](http://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Firefox_55.0_Windows_10.0%22,%22Firefox_54.0_Windows_10.0%22,%22Firefox_53.0_Windows_10.0%22,%22Firefox_52.0_Windows_10.0%22,%22Firefox_51.0_Windows_10.0%22,%22Firefox_50.0_Windows_10.0%22,%22Firefox_49.0_Windows_10.0%22,%22Firefox_48.0_Windows_10.0%22,%22Chrome_60.0.3112.78_Windows_10.0%22,%22Edge_15.15063_Windows_10.0%22,%22Safari_603.2.4_OSX_10.12.5%22,%22Edge_14.14393_Windows_10.0%22,%22Edge_13.10586_Windows_10.0%22,%22Safari_602.1.50_OSX_10.12%22,%22Safari_601.7.8_OSX_10.11.6%22,%22Safari_600.8.9_OSX_10.10.5%22,%22Safari_537.85.17_OSX_10.8.5%22,%22Safari_536.30.1_OSX_10.7.5%22,%22Safari_534.59.8_OSX_10.6.8%22,%22Chrome_59.0.3071.86_Windows_10.0%22,%22Chrome_58.0.3029.81_Windows_10.0%22,%22Chrome_57.0.2987.98_OSX_10.11.6%22%5D&releaseOptions=null&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22CSSStyleDeclaration%22) (after clicking "Expand all", and waiting a bit) illustrates one of the key issues we are facing with `CSSStyleDeclaration`.

It appears that all non-Firefox browsers implement dash-separated properties in `CSSStyleDeclaration` instances in the following way:

1. Dash-separated properties **do not** appear in `Object.getOwnPropertyNames(cssStyleDeclInstance)`;
2. Dash-separated properties **do** appear in `cssStyleDeclInstance.hasOwnProperty('property-name')`;
3. Obviously, `cssStyleDeclInstance['property-name']` reflects the correct styling data.

Since our data are based on using `Object.getOwnPropertyNames()` on prototypes and easy-to-find instances, this results in all these properties appearing to be "Firefox-specific", which, in practice, they are not.

After discussing with @foolip, it seems like the best short-term solution is to rip `CSSStyleDeclaration` out of our data set for now.

**Comment by mdittmer** [comment]
Follow-up: One of the key reasons that it seems "fairer" to remove these data is that the effect is to inflate Firefox's Browser-Specific count when Firefox is, arguably, doing "The Right Thing" by providing correctly reflecting these properties.

**Comment by foolip** [comment]
This is a all a bit odd, and @bzbarsky has kindly explained it to me in https://github.com/w3c/csswg-drafts/issues/1089 before.

The spec is here:
https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-camel-cased-attribute
https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-webkit-cased-attribute
https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-dashed-attribute

The IDL blocks are right above the anchors. Gecko does the right thing here and everyone else does something odd.

I'm thinking that simply ignoring dashed properties would be an improvement. In https://github.com/GoogleChrome/confluence/issues/171 there's also the question of CSSStyleDeclaration.WebkitBorderImage and that's mentioned in example 8 in the spec. Excluding things that start with "Webkit" would do the trick.

@mdittmer, is it a quick fix to exclude some things like this and regenerate all the graphs?

**Comment by mdittmer** [comment]
This seems fine. Should we drop dash-separated across the board, or just in `CSSStyleDeclaration`?

**Comment by foolip** [comment]
Just in `CSSStyleDeclaration` I think, I don't think they exist anywhere else but one might be surprised.

**Comment by foolip** [comment]
(I assume this can be done without collecting the data anew.)

**Comment by mdittmer** [comment]
@foolip are there browser bugs we can link to here, or just specs?

**Comment by foolip** [comment]
The Chromium bug is https://bugs.chromium.org/p/chromium/issues/detail?id=700338, I haven't filed one for Edge or WebKit.

@travisleithead @cdumez, maybe you can file bugs for Edge and WebKit?

**Comment by bzbarsky** [comment]
> Excluding things that start with "Webkit" would do the trick.

At the expense of marking as non-browser-specific things that really are browser-specific in Chrome and Safari, no?

**Comment by mdittmer** [comment]
@bzbarsky that's true. I'm not really in favour of dropping the prefixed APIs. They are "punishing" browsers for doing not-spec'd things (rather than the other way around with the hyphenated APIs).

Keep in mind that since two browsers implement them, most webkit-prefixed APIs will not show up in browser-specific counts.

**Comment by bzbarsky** [comment]
> They are "punishing" browsers for doing not-spec'd things

Except that some of the Webkit* bits are specced.

> most webkit-prefixed APIs will not show up in browser-specific counts.

Fwiw, this is an explicit concern I know @dbaron has raised about the structure of these dashboards...

One other note: https://bugs.chromium.org/p/chromium/issues/detail?id=700338 is about making the relevant props be normal IDL props, but the failure here is due to the proxy involved lying about its set of own properties, no?  The latter could be fixed without fixing the IDL issue, though of course fixing the IDL issue would also solve the problem of getOwnPropertyNames() returning bogus information.

**Comment by mdittmer** [comment]
FYI: Keeping this bug for general discussion of CSSStyleDeclaration issues. Filed separate "data hack" bug to document what tooling does (or will soon do).

**Comment by foolip** [comment]
@bzbarsky, `Object.getOwnPropertyNames(document.body.style).filter(x => x[0] == 'W')` is an empty array in both Chrome and Safari, so it currently wouldn't hide anything. But after CSSStyleDeclaration bugs are fixed they might show up, so I'm not sure what to make of that.

How about for CSSStyleDeclaration, if a property that starts with an upper case character also exists with the first character in lower case, we drop it? That would de-duplicate Gecko's webkit-prefixed CSS properties, without hiding anything unique in any other engine.

**Comment by bzbarsky** [comment]
> But after CSSStyleDeclaration bugs are fixed they might show up

Right.

> How about for CSSStyleDeclaration, if a property that starts with an upper case character also exists with the first character in lower case, we drop it?

Hmm.  I guess we can do this as an interim solution until browsers fix their `getOwnPropertyNames(CSSStyleDeclaration instance)` impls.

Another option might be is to generate a set of all possible strings that _could_ conceivably appear as properties on CSSStyleDeclaration in any browser and use hasOwnProperty in a loop instead of getOwnPropertyNames to build the list of actually supported property names).

In fact, it might be possible to generate that superset list from the list of camelcase names that browsers _do_ consistently expose, by following a few simple transformation rules...

**Comment by foolip** [comment]
>> most webkit-prefixed APIs will not show up in browser-specific counts.
>
> Fwiw, this is an explicit concern I know @dbaron has raised about the structure of these dashboards...

Yes, this is a problem, and I was surprised at how "good" Chrome/Safari looked in "browser-specific APIs" before realizing why. It also creates an unfortunate situation in "failure to ship" for Firefox where there's a lot of non-standard stuff, the kind of thing I like trying to remove. And if Firefox should want to implement them, the onus should ideally be on everyone else to write the spec and tests for it, shipping non-standard stuff is a bug.

https://github.com/GoogleChrome/confluence/issues/178 is one thing that could help us set up better incentives here, to list non-standard APIs separately, and not have them show up in "failure to ship".

**Comment by foolip** [comment]
@mdittmer, on this issue specifically, which approach do you think is the best, taking into account the value of getting this fixed quickly?

**Comment by bzbarsky** [comment]
> #178 is one thing that could help us set up better incentives here

That would be pretty awesome.

**Comment by mdittmer** [comment]
This is fixed in prod. Dash-separated properties are omitted for now.
