### ISSUE TITLE
Links to failure lists don't work in Firefox

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChrome/confluence#181]
STEPS TO REPRODUCE (in Firefox):

1. Load https://web-confluence.appspot.com/#!/confluence
2. Click "FAILURE TO SHIP".
3. Select any data point (the first data point at the "550" level for Safari, aka Safari 8.0, will do).
4. Click the little box-with-arrow after the number in the resulting popup.

EXPECTED RESULTS: Opens the actual list of things failing to ship in a new tab.  That's what it does in Chrome and Safari.  I can't test what it does with Edge, because in Edge I don't see the graph at all.

ACTUAL RESULTS: Nothing happens.

It's entirely possible that this is a Firefox issue, of course.  I'm happy to do some debugging, but it would be fairly helpful to know what the site is actually trying to do here, without having to reverse-engineer it from the minified source.

**Comment by bzbarsky** [comment]
I _think_ this ends up calling https://github.com/GoogleChrome/confluence/blob/6677a3eb49604580866cd7aa95b26ba63b44cb50/lib/chart/browser_metric_chart.es6.js#L33-L35 which calls https://github.com/GoogleChrome/confluence/blob/6677a3eb49604580866cd7aa95b26ba63b44cb50/lib/chart/browser_metric_chart.es6.js#L9-L11 but I'm not sure yet where that createNewView ends up being implemented in the end.

**Comment by mdittmer** [comment]
This is caused by using a synthetic `<a>.click()`. "Download CSV" is probably also affected. I'm half-done a fix, but probably can't land it until early next week.

**Comment by bzbarsky** [comment]
> This is caused by using a synthetic `<a>.click()`

Is the anchor not in a document?  Looks like until 8 hours ago https://github.com/whatwg/html/issues/2615 was open with discussion of what the actual behavior should be....

**Comment by bzbarsky** [comment]
Thank you!
