### ISSUE TITLE
Switch license/copyright to BSD/Chromium Authors

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/confluence#19]
Same as done with webidl-diff [here](https://github.com/GoogleChrome/webidl-diff/commit/289acb6729ccebf63c300b6f0dd97251adfb9cf1) and [here](https://github.com/GoogleChrome/webidl-diff/commit/9ef2027d90aa66a7d7e31fcafbb599601033c033).

**Comment by mdittmer** [comment]
@jingt06 PTAL at this when you get a chance. I figure you should do it rather than facing merge conflicts with any in-flight PRs you might have.

**Comment by jingt06** [comment]
#22
