### ISSUE TITLE
Rename: browser -> release; vendor -> browser

### ISSUE THREAD

**Issue by mdittmer** [GoogleChrome/confluence#58]
Based on discussion of #57 we should rename classes and variables named `browser*` (except `browserName` and `browserVersion`) to `release*`, because we intend a particular release of a browser. Similarly, comments and variable names that refer to `vendor` actually refer to a particular `browser` (which has multiple releases).

@arobins does that sound right?

**Comment by arobins** [comment]
sgtm

**Comment by mdittmer** [comment]
Fixed in 4f4d92b2983e3f8b4f1025069d85f0ca350c31e0
