### ISSUE TITLE
CSSStyleDeclaration properties missing on Firefox and Safari

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/confluence#8]
We're hoping that we can get the list of supported CSS properties showing up consistently in CSSStyleDeclaration.  In Firefox the [properties are on](https://bugzilla.mozilla.org/show_bug.cgi?id=1290786) `CSS2Properties.prototype` instead of `CSSStyleDeclaration.prototype`.  I think we had some plan for merging `CSS2Properties` "up" into `CSSStyleDeclaration`, right?  I don't see CSS2Properties members showing up in the catalog for Firefox.

In Safari, the properties appear to sort of show up as own-properties on instances of CSSStyleDeclaration:
```javascript
Object.getOwnPropertyNames(document.body.style) -> contains "borderStyle"
Object.getOwnPropertyDescriptor(document.body.style,'borderStyle') -> Object
Object.hasOwnProperty(document.body.style, 'borderStyle') -> false, WTF?
```

**Comment by RByers** [comment]
Looks like the Safari data here used to work (according to the spreadsheet), did something break?

**Comment by mdittmer** [comment]
@jingt06 this was fixed upstream in `object-graph-js`. Please provide a commit or PR link then close this.

**Comment by mdittmer** [comment]
This has been fixed for Safari via https://github.com/mdittmer/object-graph-js/commit/3f085717d50b538ec762ff8031b54f2709397f8c but `CSS2Properties` is the top-level-prototype for `foo.style`in Firefox. We need to copy its API surface into `CSSStyleDeclaration` in order to fake this for Firefox.

**Comment by mdittmer** [comment]
This has been fixed for Firefox via a data update.
