### ISSUE TITLE
window.Screen APIs are (mostly) missing

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/confluence#91]
`window.Screen.prototype` should have a bunch of properties eg. `availTop`, but I don't see them in the raw data (Except for a couple Chrome releases under an interface named `)`)).

**Comment by mdittmer** [comment]
This is fixed with last night's data push. Raw object graph data on https://github.com/GoogleChrome/confluence/commit/ed13a99116ec36b61661b9f7be2edc413d589934 has been processed and pushed to Datastore.
